package pilots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dominictracey/rugby-scores/models"
)

// FindPilotsOKCode is the HTTP code returned for type FindPilotsOK
const FindPilotsOKCode int = 200

/*FindPilotsOK list the Pilot operations

swagger:response findPilotsOK
*/
type FindPilotsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Pilot `json:"body,omitempty"`
}

// NewFindPilotsOK creates FindPilotsOK with default headers values
func NewFindPilotsOK() *FindPilotsOK {
	return &FindPilotsOK{}
}

// WithPayload adds the payload to the find pilots o k response
func (o *FindPilotsOK) WithPayload(payload []*models.Pilot) *FindPilotsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find pilots o k response
func (o *FindPilotsOK) SetPayload(payload []*models.Pilot) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindPilotsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Pilot, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*FindPilotsDefault generic error response

swagger:response findPilotsDefault
*/
type FindPilotsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindPilotsDefault creates FindPilotsDefault with default headers values
func NewFindPilotsDefault(code int) *FindPilotsDefault {
	if code <= 0 {
		code = 500
	}

	return &FindPilotsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find pilots default response
func (o *FindPilotsDefault) WithStatusCode(code int) *FindPilotsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find pilots default response
func (o *FindPilotsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find pilots default response
func (o *FindPilotsDefault) WithPayload(payload *models.Error) *FindPilotsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find pilots default response
func (o *FindPilotsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindPilotsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
