runtime: go
env: flex

# beta_settings:
#   # Enable Google Cloud Endpoints API management.
#   use_endpoints_api_management: true
#   # Specify the Open API specification.
#   endpoints_swagger_spec_file: openapi.yaml
endpoints_api_service:
  # The following values are to be replaced by information from the output of
  # 'gcloud service-management deploy openapi.yaml' command.
  name: scores-api
  config_id: 2017-05-03r0
