package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AuthInfoGoogleJwtHandlerFunc turns a function with the right signature into a auth info google jwt handler
type AuthInfoGoogleJwtHandlerFunc func(AuthInfoGoogleJwtParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AuthInfoGoogleJwtHandlerFunc) Handle(params AuthInfoGoogleJwtParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AuthInfoGoogleJwtHandler interface for that can handle valid auth info google jwt params
type AuthInfoGoogleJwtHandler interface {
	Handle(AuthInfoGoogleJwtParams, interface{}) middleware.Responder
}

// NewAuthInfoGoogleJwt creates a new http.Handler for the auth info google jwt operation
func NewAuthInfoGoogleJwt(ctx *middleware.Context, handler AuthInfoGoogleJwtHandler) *AuthInfoGoogleJwt {
	return &AuthInfoGoogleJwt{Context: ctx, Handler: handler}
}

/*AuthInfoGoogleJwt swagger:route GET /auth/info/googlejwt authInfoGoogleJwt

Returns the requests' authentication information.

*/
type AuthInfoGoogleJwt struct {
	Context *middleware.Context
	Handler AuthInfoGoogleJwtHandler
}

func (o *AuthInfoGoogleJwt) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewAuthInfoGoogleJwtParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
