package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dominictracey/rugby-scores/models"
)

// AuthInfoGoogleIDTokenOKCode is the HTTP code returned for type AuthInfoGoogleIDTokenOK
const AuthInfoGoogleIDTokenOKCode int = 200

/*AuthInfoGoogleIDTokenOK Authentication info.

swagger:response authInfoGoogleIdTokenOK
*/
type AuthInfoGoogleIDTokenOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuthInfoResponse `json:"body,omitempty"`
}

// NewAuthInfoGoogleIDTokenOK creates AuthInfoGoogleIDTokenOK with default headers values
func NewAuthInfoGoogleIDTokenOK() *AuthInfoGoogleIDTokenOK {
	return &AuthInfoGoogleIDTokenOK{}
}

// WithPayload adds the payload to the auth info google Id token o k response
func (o *AuthInfoGoogleIDTokenOK) WithPayload(payload *models.AuthInfoResponse) *AuthInfoGoogleIDTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth info google Id token o k response
func (o *AuthInfoGoogleIDTokenOK) SetPayload(payload *models.AuthInfoResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthInfoGoogleIDTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
