package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dominictracey/rugby-scores/models"
)

// AuthInfoFirebaseOKCode is the HTTP code returned for type AuthInfoFirebaseOK
const AuthInfoFirebaseOKCode int = 200

/*AuthInfoFirebaseOK Authentication info.

swagger:response authInfoFirebaseOK
*/
type AuthInfoFirebaseOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuthInfoResponse `json:"body,omitempty"`
}

// NewAuthInfoFirebaseOK creates AuthInfoFirebaseOK with default headers values
func NewAuthInfoFirebaseOK() *AuthInfoFirebaseOK {
	return &AuthInfoFirebaseOK{}
}

// WithPayload adds the payload to the auth info firebase o k response
func (o *AuthInfoFirebaseOK) WithPayload(payload *models.AuthInfoResponse) *AuthInfoFirebaseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth info firebase o k response
func (o *AuthInfoFirebaseOK) SetPayload(payload *models.AuthInfoResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthInfoFirebaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
