package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/dominictracey/rugby-scores/models"
)

// AuthInfoFirebaseHandlerFunc turns a function with the right signature into a auth info firebase handler
type AuthInfoFirebaseHandlerFunc func(AuthInfoFirebaseParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn AuthInfoFirebaseHandlerFunc) Handle(params AuthInfoFirebaseParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// AuthInfoFirebaseHandler interface for that can handle valid auth info firebase params
type AuthInfoFirebaseHandler interface {
	Handle(AuthInfoFirebaseParams, *models.Principal) middleware.Responder
}

// NewAuthInfoFirebase creates a new http.Handler for the auth info firebase operation
func NewAuthInfoFirebase(ctx *middleware.Context, handler AuthInfoFirebaseHandler) *AuthInfoFirebase {
	return &AuthInfoFirebase{Context: ctx, Handler: handler}
}

/*AuthInfoFirebase swagger:route GET /auth/info/firebase authInfoFirebase

Returns the requests' authentication information.

*/
type AuthInfoFirebase struct {
	Context *middleware.Context
	Handler AuthInfoFirebaseHandler
}

func (o *AuthInfoFirebase) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewAuthInfoFirebaseParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
