package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AuthInfoGoogleIDTokenHandlerFunc turns a function with the right signature into a auth info google Id token handler
type AuthInfoGoogleIDTokenHandlerFunc func(AuthInfoGoogleIDTokenParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn AuthInfoGoogleIDTokenHandlerFunc) Handle(params AuthInfoGoogleIDTokenParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// AuthInfoGoogleIDTokenHandler interface for that can handle valid auth info google Id token params
type AuthInfoGoogleIDTokenHandler interface {
	Handle(AuthInfoGoogleIDTokenParams, interface{}) middleware.Responder
}

// NewAuthInfoGoogleIDToken creates a new http.Handler for the auth info google Id token operation
func NewAuthInfoGoogleIDToken(ctx *middleware.Context, handler AuthInfoGoogleIDTokenHandler) *AuthInfoGoogleIDToken {
	return &AuthInfoGoogleIDToken{Context: ctx, Handler: handler}
}

/*AuthInfoGoogleIDToken swagger:route GET /auth/info/googleidtoken authInfoGoogleIdToken

Returns the requests' authentication information.

*/
type AuthInfoGoogleIDToken struct {
	Context *middleware.Context
	Handler AuthInfoGoogleIDTokenHandler
}

func (o *AuthInfoGoogleIDToken) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewAuthInfoGoogleIDTokenParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
