package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dominictracey/rugby-scores/models"
)

// AuthInfoGoogleJwtOKCode is the HTTP code returned for type AuthInfoGoogleJwtOK
const AuthInfoGoogleJwtOKCode int = 200

/*AuthInfoGoogleJwtOK Authentication info.

swagger:response authInfoGoogleJwtOK
*/
type AuthInfoGoogleJwtOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuthInfoResponse `json:"body,omitempty"`
}

// NewAuthInfoGoogleJwtOK creates AuthInfoGoogleJwtOK with default headers values
func NewAuthInfoGoogleJwtOK() *AuthInfoGoogleJwtOK {
	return &AuthInfoGoogleJwtOK{}
}

// WithPayload adds the payload to the auth info google jwt o k response
func (o *AuthInfoGoogleJwtOK) WithPayload(payload *models.AuthInfoResponse) *AuthInfoGoogleJwtOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth info google jwt o k response
func (o *AuthInfoGoogleJwtOK) SetPayload(payload *models.AuthInfoResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthInfoGoogleJwtOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
