package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dominictracey/rugby-scores/models"
)

// EchoOKCode is the HTTP code returned for type EchoOK
const EchoOKCode int = 200

/*EchoOK Echo

swagger:response echoOK
*/
type EchoOK struct {

	/*
	  In: Body
	*/
	Payload *models.EchoMessage `json:"body,omitempty"`
}

// NewEchoOK creates EchoOK with default headers values
func NewEchoOK() *EchoOK {
	return &EchoOK{}
}

// WithPayload adds the payload to the echo o k response
func (o *EchoOK) WithPayload(payload *models.EchoMessage) *EchoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the echo o k response
func (o *EchoOK) SetPayload(payload *models.EchoMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EchoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
