package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A simple Google Cloud Endpoints API example.",
    "title": "Endpoints Example",
    "version": "1.0.0"
  },
  "host": "echo-api.endpoints.rugby-scores-7.cloud.goog",
  "basePath": "/",
  "paths": {
    "/auth/info/firebase": {
      "get": {
        "description": "Returns the requests' authentication information.",
        "produces": [
          "application/json"
        ],
        "operationId": "authInfoFirebase",
        "security": [
          {
            "firebase": []
          }
        ],
        "responses": {
          "200": {
            "description": "Authentication info.",
            "schema": {
              "$ref": "#/definitions/authInfoResponse"
            }
          }
        }
      }
    },
    "/echo": {
      "post": {
        "description": "Echo back a given message.",
        "produces": [
          "application/json"
        ],
        "operationId": "echo",
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "description": "Message to echo",
            "name": "message",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/echoMessage"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Echo",
            "schema": {
              "$ref": "#/definitions/echoMessage"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "authInfoResponse": {
      "properties": {
        "email": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "echoMessage": {
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "principal": {
      "type": "string"
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "key",
      "in": "query"
    },
    "firebase": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "https://changemeplz.com",
      "x-google-audiences": "rugby-scores-7",
      "x-google-issuer": "https://securetoken.google.com/rugby-scores-7",
      "x-google-jwks_uri": "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    }
  }
}`))
}
