package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Submit and view scores",
    "title": "Rugby Scores API",
    "version": "1.0.0"
  },
  "host": "scores-api.endpoints.rugby-scores-7.cloud.goog",
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "tags": [
          "Pilots"
        ],
        "operationId": "findPilots",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "since",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list the Pilot operations",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/pilot"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "Pilots"
        ],
        "operationId": "addOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/pilot"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/pilot"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/auth/info/auth0": {
      "get": {
        "description": "Returns the requests' authentication information.",
        "produces": [
          "application/json"
        ],
        "operationId": "auth_info_auth0_jwk",
        "security": [
          {
            "auth0_jwk": []
          }
        ],
        "responses": {
          "200": {
            "description": "Authentication info.",
            "schema": {
              "$ref": "#/definitions/authInfoResponse"
            }
          }
        }
      }
    },
    "/auth/info/firebase": {
      "get": {
        "description": "Returns the requests' authentication information.",
        "produces": [
          "application/json"
        ],
        "operationId": "authInfoFirebase",
        "security": [
          {
            "firebase": []
          }
        ],
        "responses": {
          "200": {
            "description": "Authentication info.",
            "schema": {
              "$ref": "#/definitions/authInfoResponse"
            }
          }
        }
      }
    },
    "/auth/info/googleidtoken": {
      "get": {
        "description": "Returns the requests' authentication information.",
        "produces": [
          "application/json"
        ],
        "operationId": "authInfoGoogleIdToken",
        "security": [
          {
            "google_id_token": []
          }
        ],
        "responses": {
          "200": {
            "description": "Authentication info.",
            "schema": {
              "$ref": "#/definitions/authInfoResponse"
            }
          }
        }
      }
    },
    "/auth/info/googlejwt": {
      "get": {
        "description": "Returns the requests' authentication information.",
        "produces": [
          "application/json"
        ],
        "operationId": "auth_info_google_jwt",
        "security": [
          {
            "google_jwt": []
          }
        ],
        "responses": {
          "200": {
            "description": "Authentication info.",
            "schema": {
              "$ref": "#/definitions/authInfoResponse"
            }
          }
        }
      }
    },
    "/echo": {
      "post": {
        "description": "Echo back a given message.",
        "produces": [
          "application/json"
        ],
        "operationId": "echo",
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "description": "Message to echo",
            "name": "message",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/echoMessage"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Echo",
            "schema": {
              "$ref": "#/definitions/echoMessage"
            }
          }
        }
      }
    },
    "/{id}": {
      "put": {
        "tags": [
          "Pilots"
        ],
        "operationId": "updateOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/pilot"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/pilot"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Pilots"
        ],
        "operationId": "destroyOne",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "authInfoResponse": {
      "properties": {
        "email": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "echoMessage": {
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "pilot": {
      "type": "object",
      "properties": {
        "Address": {
          "type": "string",
          "minLength": 1
        },
        "ID": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "Licensed": {
          "type": "boolean"
        },
        "Name": {
          "type": "string",
          "minLength": 1
        },
        "Phone": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "key",
      "in": "query"
    },
    "auth0_jwk": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "https://YOUR-ACCOUNT-NAME.auth0.com/authorize",
      "x-google-audiences": "YOUR-CLIENT-ID",
      "x-google-issuer": "https://YOUR-ACCOUNT-NAME.auth0.com/",
      "x-google-jwks_uri": "https://YOUR-ACCOUNT-NAME.auth0.com/.well-known/jwks.json"
    },
    "firebase": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "https://foo.bar/",
      "x-google-audiences": "YOUR-PROJECT-ID",
      "x-google-issuer": "https://securetoken.google.com/YOUR-PROJECT-ID",
      "x-google-jwks_uri": "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    },
    "google_id_token": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "https://foo.bar/",
      "x-google-audiences": "YOUR-CLIENT-ID",
      "x-google-issuer": "https://accounts.google.com",
      "x-google-jwks_uri": "https://www.googleapis.com/oauth2/v3/certs"
    },
    "google_jwt": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "https://foo.bar/",
      "x-google-audiences": "echo.endpoints.sample.google.com",
      "x-google-issuer": "jwt-client.endpoints.sample.google.com",
      "x-google-jwks_uri": "https://www.googleapis.com/service_accounts/v1/jwk/YOUR-SERVICE-ACCOUNT-EMAIL"
    }
  }
}`))
}
