package pilot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dominictracey/rugby-scores/models"
)

// AddOnePilotCreatedCode is the HTTP code returned for type AddOnePilotCreated
const AddOnePilotCreatedCode int = 201

/*AddOnePilotCreated Created

swagger:response addOnePilotCreated
*/
type AddOnePilotCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Pilot `json:"body,omitempty"`
}

// NewAddOnePilotCreated creates AddOnePilotCreated with default headers values
func NewAddOnePilotCreated() *AddOnePilotCreated {
	return &AddOnePilotCreated{}
}

// WithPayload adds the payload to the add one pilot created response
func (o *AddOnePilotCreated) WithPayload(payload *models.Pilot) *AddOnePilotCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add one pilot created response
func (o *AddOnePilotCreated) SetPayload(payload *models.Pilot) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddOnePilotCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AddOnePilotDefault error

swagger:response addOnePilotDefault
*/
type AddOnePilotDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddOnePilotDefault creates AddOnePilotDefault with default headers values
func NewAddOnePilotDefault(code int) *AddOnePilotDefault {
	if code <= 0 {
		code = 500
	}

	return &AddOnePilotDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add one pilot default response
func (o *AddOnePilotDefault) WithStatusCode(code int) *AddOnePilotDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add one pilot default response
func (o *AddOnePilotDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add one pilot default response
func (o *AddOnePilotDefault) WithPayload(payload *models.Error) *AddOnePilotDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add one pilot default response
func (o *AddOnePilotDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddOnePilotDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
