package pilot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dominictracey/rugby-scores/models"
)

// DestroyOnePilotNoContentCode is the HTTP code returned for type DestroyOnePilotNoContent
const DestroyOnePilotNoContentCode int = 204

/*DestroyOnePilotNoContent Deleted

swagger:response destroyOnePilotNoContent
*/
type DestroyOnePilotNoContent struct {
}

// NewDestroyOnePilotNoContent creates DestroyOnePilotNoContent with default headers values
func NewDestroyOnePilotNoContent() *DestroyOnePilotNoContent {
	return &DestroyOnePilotNoContent{}
}

// WriteResponse to the client
func (o *DestroyOnePilotNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*DestroyOnePilotDefault error

swagger:response destroyOnePilotDefault
*/
type DestroyOnePilotDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDestroyOnePilotDefault creates DestroyOnePilotDefault with default headers values
func NewDestroyOnePilotDefault(code int) *DestroyOnePilotDefault {
	if code <= 0 {
		code = 500
	}

	return &DestroyOnePilotDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the destroy one pilot default response
func (o *DestroyOnePilotDefault) WithStatusCode(code int) *DestroyOnePilotDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the destroy one pilot default response
func (o *DestroyOnePilotDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the destroy one pilot default response
func (o *DestroyOnePilotDefault) WithPayload(payload *models.Error) *DestroyOnePilotDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the destroy one pilot default response
func (o *DestroyOnePilotDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DestroyOnePilotDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
