package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Pilot pilot
// swagger:model pilot
type Pilot struct {

	// created at
	CreatedAt strfmt.DateTime `json:"createdAt,omitempty"`

	// first name
	FirstName string `json:"firstName,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// last modified
	LastModified strfmt.DateTime `json:"lastModified,omitempty"`

	// last name
	LastName string `json:"lastName,omitempty"`

	// licensed
	Licensed bool `json:"licensed,omitempty"`
}

// Validate validates this pilot
func (m *Pilot) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
